backend:
  name: git-gateway
  branch: master
  site_url: https://famous-kelpie-39eeb1.netlify.app
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

local_backend: true

# Media and public assets
media_folder: static/images
public_folder: /images

# Collections
collections:
  # Pages collection
  - name: pages
    label: Pagina's
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "SEO Beschrijving", name: "description", widget: "text"}
      - {
          label: "Content",
          name: "body",
          widget: "markdown",
          sanitize_preview: true,
          editor_components: ["image"],
          buttons: ["bold", "italic", "code", "link", "bulleted-list", "numbered-list", "heading-one", "heading-two", "heading-three", "quote"],
          modes: ["raw", "rich_text"],
          editor_css: ".nc-controlPane-widget { min-height: 400px; } .nc-controlPane-widget .CodeMirror { height: auto; } .nc-controlPane-widget .CodeMirror-scroll { min-height: 400px; }"
        }
      - {label: "Publicatie Datum", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}

  # Services collection
  - name: services
    label: Diensten
    folder: content/services
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "SEO Beschrijving", name: "description", widget: "text"}
      - {
          label: "Content",
          name: "body",
          widget: "markdown",
          sanitize_preview: true,
          editor_components: ["image"],
          buttons: ["bold", "italic", "code", "link", "bulleted-list", "numbered-list", "heading-one", "heading-two", "heading-three", "quote"],
          modes: ["raw", "rich_text"],
          editor_css: ".nc-controlPane-widget { min-height: 400px; } .nc-controlPane-widget .CodeMirror { height: auto; } .nc-controlPane-widget .CodeMirror-scroll { min-height: 400px; }"
        }
      - {label: "Icon", name: "icon", widget: "image", required: true}
      - {label: "Volgorde", name: "weight", widget: "number", default: 1}

  # Settings collection
  - name: settings
    label: Instellingen
    files:
      - name: general
        label: Algemene Instellingen
        file: content/settings/general.yml
        fields:
          - {label: "Site Naam", name: "site_name", widget: "string"}
          - {label: "Site Beschrijving", name: "site_description", widget: "text"}
          - label: "Contact Info"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Telefoon", name: "phone", widget: "string"}
              - {label: "Adres", name: "address", widget: "text"}
